### ISSUE TITLE
Use of `wait_readable` and `wait_writable`.

### ISSUE THREAD

**Issue by ioquatix** [paddor/cztop#20] opened 2024-01-05 22:03 UTC
Does `Zmsg` use Ruby's internal IO operations?

[Otherwise, I'd recommend](https://github.com/paddor/cztop/commit/e07d99f1d5372a644814254c3b239151d9e0af0f#diff-9f01f409a074e17e4814d5218a6747f1fb4aaa4c41856968a4d3596248cb8806R64):

```suggestion
      destination.wait_writable
```

Because the internal design of the Ruby scheduler, if `Zmsg` is invoking `recv/send` or similar operations directly, it will prevent even Ruby threads from context switching (unless it also releases the GVL). I'll go take a look at `Zmsg` to see what it does.

**Comment by paddor** [comment] 2024-01-05 22:12
It does, because `destination` is a `CZTop::Socket`, which includes `SendReceiveMethods`, where `#wait_readable`  and `#wait_writable` are implemented using an `IO` object for the ZMQ socket FD. That FD is only used to signal readability/writabilty, not for actual IO.

It's possible that the GVL is not released while queueing/unqueing a message in/from a ZMQ socket. But those actions happen in an instant because ZMQ will do the actual IO in another thread. Releasing the GVL might not be so easy given that this library is built on generated FFI code (czmq-ffi-gen).

**Comment by paddor** [comment] 2024-01-05 22:31
Thinking about it a bit more, I think this is what you're looking for: https://github.com/zeromq/czmq/blob/master/bindings/ruby/lib/czmq/ffi.rb#L53

I think that means that the GVL is released during the FFI function call? Please correct me if I'm wrong.

**Comment by ioquatix** [comment] 2024-01-06 06:25
> I think that means that the GVL is released during the FFI function call? Please correct me if I'm wrong.

Yes, IIRC, that's correct. cc @larskanis who may be able to provide more clarification.

> It does, because destination is a CZTop::Socket, which includes SendReceiveMethods, ...

Your proposed implementation is a reasonable compromise provided there is only one `read` or `write` system call. Even in the presence of threads, using `wait_readable` or `wait_writable` can be a good idea, so you can consider dropping `if Fiber.scheduler` etc.

Is the actual `read`/`write` system call invoked by native zmsg implementation?

**Comment by paddor** [comment] 2024-01-06 08:15
I tried to remove `if Fiber.scheduler` and it works for a simple script that uses threads for concurrency. But it breaks some of the specs. I can look into it.

Not sure how familiar you are with ZMQ, but ZMQ sockets are a [little different](https://zguide.zeromq.org). It deals in atomic messages. The actual IO (inproc, IPC, TCP, ...) happens in one or more ZMQ IO threads. An FD is provided for integration into an event loop, which can have flukes.. E.g. when the FD looks readable, you still have to check the actual availability of a message by reading out its events, as described [here](https://libzmq.readthedocs.io/en/latest/zmq_getsockopt.html#_zmq_events_retrieve_socket_event_state):

>The combination of a file descriptor returned by the 'ZMQ_FD' option being ready for reading but no actual events returned by a subsequent retrieval of the 'ZMQ_EVENTS' option is valid; applications should simply ignore this case and restart their polling operation/event loop.

CZMQ is a convenience layer on top of libzmq to make it feel more OOP, and other additional functionality.

Does that answer your question?

**Comment by ioquatix** [comment] 2024-01-06 09:08
Yes that makes sense. So the descriptor is provided as a readiness notification.

**Comment by paddor** [comment] 2024-01-07 03:46
I've refactored a few things and now it always calls `#wait_readable` or `#wait_writable`.

**Comment by larskanis** [comment] 2024-01-07 11:25
There is a tool to test correctness of the Fiber.scheduler support, that I wrote for the pg gem. It is [in the ruby-pg repo](https://github.com/ged/ruby-pg/blob/5c105f227ac2b32331c0006b109688f6c7c9ed64/spec/helpers/tcp_gate_scheduler.rb#L3C70-L3C70) but it is very generic. It supports TCP connections only so far. If there is some interest to use it in other projects, I can extract the TcpGateScheduler into its own gem.

The problem without that tool is, that you don't notice, that some C library code does IO blocking operations, that should be handled through the Fiber.scheduler instead. If the library is prepared for an event loop and provides a few file descriptors to be observed and the library is carefully implemented to pass any IO blocking operations through them, than there is maybe no need to do more specific tests. But ruby-pg would be completely buggy in regards to Fiber.scheduler, if it wouldn't [have tested](https://github.com/ged/ruby-pg/blob/5c105f227ac2b32331c0006b109688f6c7c9ed64/spec/pg/scheduler_spec.rb#L11) it with the TcpGateScheduler.

This is because libpq has no central support for an event loop, but has dedicated functions to establish a connection in a non-blocking way, to read data in a non-blocking way, to write data in a non-blocking way. Also there are many functions that do internal round trips to the server that needs to be handled specifically to avoid these potentially blocking states. Last but not least there are functions that aren't available as a non-blocking version at all, so they have to be re-implemented in Ruby or must be executed in a dedicated thread.

If __all__ potentially blocking situations of the underlying library are passed through the Fiber.scheduler there is (theoretically) no need to use `attach_function blocking:true` any longer. This is because waiting through the scheduler always unlocks the GVL, so that other threads can run. In practice unlocking the GVL can still be useful to allow other ruby threads while CPU intensive function calls. Also the TcpGateScheduler needs GVL unlocked, to detect incorrect implementations. The downside is that `blocking: true` is a little bit slower, but not much.

**Comment by paddor** [comment] 2024-01-07 21:03
@larskanis Thanks for the explanation. That was the exact issue that I had here. I needed to be sure that the native functions won't block. Now, by always invoking `SendReceiveMethods#wait_readable` and `#wait_writable`, the native functions are only called when it's been determined that they won't block.

Also, using the newly added [massive_async.rb](https://github.com/paddor/cztop/blob/master/examples/massive_async.rb) script, I can confirm that FFI `attach_function` with `blocking: true` is not much slower than `blocking: false`.

With `blocking: true`:
```
$ ruby -v ./massive_async.rb
ruby 3.3.0 (2023-12-25 revision 5124f9ac75) [x86_64-linux]
CZMQ::FFI: Attaching functions with options: {:blocking=>true}
5 REP sockets serving requests from 200 REQ sockets.
Each REQ socket will send 1000 requests.
. = 1000 requests
........................................................................................................................................................................................................
REP at inproc://req_rep_example0 served 40000 requests.
REP at inproc://req_rep_example1 served 40000 requests.
REP at inproc://req_rep_example2 served 40000 requests.
REP at ipc:///tmp/req_rep_example0 served 40000 requests.
REP at tcp://localhost:5556 served 40000 requests.
200000 requests in 15.32s = 13.1k r/s
```

With `blocking: false`:
```
$ ruby -v ./massive_async.rb
ruby 3.3.0 (2023-12-25 revision 5124f9ac75) [x86_64-linux]
CZMQ::FFI: Attaching functions with options: {:blocking=>false}
5 REP sockets serving requests from 200 REQ sockets.
Each REQ socket will send 1000 requests.
. = 1000 requests
........................................................................................................................................................................................................
REP at inproc://req_rep_example0 served 40000 requests.
REP at inproc://req_rep_example1 served 40000 requests.
REP at inproc://req_rep_example2 served 40000 requests.
REP at ipc:///tmp/req_rep_example0 served 40000 requests.
REP at tcp://localhost:5556 served 40000 requests.
200000 requests in 13.54s = 14.8k r/s
```

So 13.1k vs 14.8k requests per second.
With the JIT enabled, it's 16.9k vs 18.9k.

With the new guarantee that the native functions don't block, one could consider providing a way to attach the functions with `blocking: false`. I've yet to run into performance problems caused by ZMQ or this gem. Encoding/decoding and transport of messages usually proves to be just a tiny fraction of an application's resource usage.

**Comment by paddor** [comment] 2024-01-07 21:23
@larskanis Yeah no, `blocking: false` is not gonna happen any time soon. For example [this](https://github.com/paddor/cztop/blob/v1.2.2/perf/inproc_lat.rb) perf script uses `zsock_signal()` and `zsock_wait()` to coordinate the two threads. With `blocking: false` it hangs because the GVL isn't released.

Given that czmq-ffi-gen's FFI code is 100% generated, and CZMQ's [API definitions](https://github.com/zeromq/czmq/blob/master/api/zsock.api#L373-L389) don't specify whether a function blocks, the [generator script](https://github.com/zeromq/zproject/blob/master/zproject_ruby.gsl) has no way of knowing when to use `blocking: true` or `blocking: false`. Also, things would get way more complex.

For now, I'll leave it as it is.

**Comment by paddor** [comment] 2024-01-07 21:29
@ioquatix I've restored compatibility with Ruby 3.0+ by defining `IO::TimeoutError < IOError` in case it's not defined. The few specs that use Async are happy, even with Async v1. I've also fixed some newly introduced latency issues.

**Comment by larskanis** [comment] 2024-01-08 09:44
> Yeah no, `blocking: false` is not gonna happen any time soon. For example [this](https://github.com/paddor/cztop/blob/v1.2.2/perf/inproc_lat.rb) perf script uses `zsock_signal()` and `zsock_wait()` to coordinate the two threads. With `blocking: false` it hangs because the GVL isn't released.

Unfortunately this is a very safe sign, that `CZTop::Socket::PAIR#wait` is not Fiber.scheduler compatible. It obviously blocks within the libzmq, without passing the waiting state through the scheduler.

**Comment by paddor** [comment] 2024-01-08 10:45
You're absolutely right. I should mention that in the API documentation for `#signal` and `#wait`, since there's no FD available for those and therefore they're incompatible with the Fiber.scheduler.

**Comment by paddor** [comment] 2024-01-16 10:41
v1.2.4 released. Closing this issue. Reopen if needed.

**Closed as completed by paddor** 2024-01-16 10:41 UTC

**Comment by ioquatix** [comment] 2024-01-16 11:50
Just a small note - while blocking the scheduler isn't ideal, it's also not the end of the world. It will definitely affect throughput, but I like to think of things in terms of magnitude rather than absolutes.
